### ISSUE TITLE
Tensorflow pickling issue

### ISSUE THREAD

**Issue by TorokLev** [pyhopper/pyhopper#2]

**Comment by TorokLev** [comment]
Hi,

For some reason Tensorflow objects in objective function implemented as a class have a problem in pickling.

Good:

    import pyhopper as ph
    
    search = ph.Search(
        val=ph.float(0, 1)
    )
    
    
    def obj_func(params):
        predicted = model.predict(np.array([ params['val'], -8.58276875e-02,  1.67481071e-02,  
                                            1.38237864e-02,
             4.36567377e-04, -9.57481593e-01,  9.36076555e-02,  2.66115899e-01]))[0][0]
        return predicted
    
    res=search.run(
        obj_func,
        steps=100,
        n_jobs=10,
    )
    res


Wrong: 

      import pyhopper as ph
      
      search = ph.Search(
          val=ph.float(0, 1)
      )
      
      class Obj:
          def __init__(self, model):
              self.model = model
          
          def __call__(params):
              predicted = self.model.predict(np.array([ params['val'], -8.58276875e-02,  1.67481071e-02,  
                                              1.38237864e-02,
               4.36567377e-04, -9.57481593e-01,  9.36076555e-02,  2.66115899e-01]))[0][0]
              return predicted
      
      obj_func = Obj(model)
      
      res=search.run(
          obj_func,
          steps=100,
          n_jobs=10,
      )
      

Throws this error:


    _RemoteTraceback                          Traceback (most recent call last)
    _RemoteTraceback: 
    """
    Traceback (most recent call last):
      File "/usr/lib/python3.10/multiprocessing/queues.py", line 244, in _feed
        obj = _ForkingPickler.dumps(obj)
      File "/usr/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
        cls(buf, protocol).dump(obj)
    TypeError: cannot pickle 'tensorflow.lite.python.interpreter_wrapper._pywrap_tensorflow_interpreter_wrapper.InterpreterWrapper' object
    """
    
    The above exception was the direct cause of the following exception:
    
    TypeError                                 Traceback (most recent call last)
    Cell In [91], line 19
         15         return predicted
         17 obj_func = Obj(model)
    ---> 19 res=search.run(
         20     obj_func,
         21     steps=100,
         22     n_jobs=10,
         23 )
    
    File /usr/local/lib/python3.10/dist-packages/pyhopper/search.py:756, in Search.run(self, objective_function, direction, runtime, steps, endless_mode, seeding_steps, seeding_runtime, seeding_ratio, pruner, n_jobs, quiet, ignore_nans, mp_backend, enable_rejection_cache, callbacks, start_temperature, end_temperature, kwargs, checkpoint_path, overwrite_checkpoint, keep_history)
        754     schedule.increment_step()
        755     # Before entering the loop, let's wait until we can run at least one candidate
    --> 756     self._wait_for_one_free_executor()
        758 self._run_context.terminate = True
        759 self._wait_for_all_running_jobs()
    
    File /usr/local/lib/python3.10/dist-packages/pyhopper/search.py:487, in Search._wait_for_one_free_executor(self)
        483 if self._run_context.task_executor.is_full:
        484     # Queue is full, let's wait at least until 1 task is done before submitting this one
        485     self._run_context.task_executor.wait_for_first_to_complete()
    --> 487 for (
        488     candidate,
        489     param_info,
        490     candidate_result,
        491 ) in self._run_context.task_executor.iterate_done_tasks():
        492     self._async_result_ready(candidate, param_info, candidate_result)
    
    File /usr/local/lib/python3.10/dist-packages/pyhopper/parallel.py:410, in TaskManager.iterate_done_tasks(self)
        408     self._pending_futures.pop(i)
        409     self._pending_candidates.pop(i)
    --> 410     yield candidate, param_info, future.result()
        411 else:
        412     i += 1
    
    File /usr/lib/python3.10/concurrent/futures/_base.py:451, in Future.result(self, timeout)
        449     raise CancelledError()
        450 elif self._state == FINISHED:
    --> 451     return self.__get_result()
        453 self._condition.wait(timeout)
        455 if self._state in [CANCELLED, CANCELLED_AND_NOTIFIED]:
    
    File /usr/lib/python3.10/concurrent/futures/_base.py:403, in Future.__get_result(self)
        401 if self._exception:
        402     try:
    --> 403         raise self._exception
        404     finally:
        405         # Break a reference cycle with the exception in self._exception
        406         self = None
    
    File /usr/lib/python3.10/multiprocessing/queues.py:244, in Queue._feed(buffer, notempty, send_bytes, writelock, reader_close, writer_close, ignore_epipe, onerror, queue_sem)
        241     return
        243 # serialize the data before acquiring the lock
    --> 244 obj = _ForkingPickler.dumps(obj)
        245 if wacquire is None:
        246     send_bytes(obj)
    
    File /usr/lib/python3.10/multiprocessing/reduction.py:51, in ForkingPickler.dumps(cls, obj, protocol)
         48 @classmethod
         49 def dumps(cls, obj, protocol=None):
         50     buf = io.BytesIO()
    ---> 51     cls(buf, protocol).dump(obj)
         52     return buf.getbuffer()
    
    TypeError: cannot pickle 'tensorflow.lite.python.interpreter_wrapper._pywrap_tensorflow_interpreter_wrapper.InterpreterWrapper' object
